### ISSUE TITLE
Saving a photo with a contact

### ISSUE THREAD

**Issue by daerimin** [blainepwnz/AndroidContacts#1]
Hello,

First off, excellent library - thank you!!

I am trying to save a photo to a contact, and it doesn't appear to be working.  I have a drawable in my app, which I want to use as a contact photo.  I am doing:

`contact.setPhotoUri(Uri.parse("android.resource://com.[redacted]/drawable/my_logo"))`

then using ContactsSaverBuilder to save the data.  But, when viewing the contact, there is no photo.  Can you help?

**Comment by blainepwnz** [comment]
#4 better late than never :)
@daerimin fixed your issue, if it is still relevant
