### ISSUE TITLE
Telegram Viber and Whatsap

### ISSUE THREAD

**Issue by hrupin** [blainepwnz/AndroidContacts#12]
Hello! Great library, thanks for it.

And is it possible to get information about the social networks of the contact? Telegram Viber and Whatsap, as an android phone book.

I managed to get in the accountType: org.telegram.messenger or com.google. 
How to get the whole list?

Thanks in advance for your help

**Comment by blainepwnz** [comment]
Hello!
I think you can filter them manually after you get the list.
Library has built-in filters, but they are implemented pretty bad.
