### ISSUE TITLE
AccountName and AccountType

### ISSUE THREAD

**Issue by dimitars84** [blainepwnz/AndroidContacts#13]
Hi,
I am using your library to fetch contacts information, but there is problem with getting AccountName and AccountType. 
If the contact is from google account, I get that value, but if its from SIM card I get only null.

**Comment by blainepwnz** [comment]
Hi,
Sorry for delay, github decided not to sent me any email about your issue.
According to some articles and stackoverflow it depends from vendor what account type and name is assigned to contact.
So on my own vivo device I get both account type and name for sim account, at the same time sim account type and name on emulator are null.
