### ISSUE TITLE
getGroupList() always returns an empty list?

### ISSUE THREAD

**Issue by JedrzejBlaszczak** [blainepwnz/AndroidContacts#17]
Hello,
I am having a problem with obtaining the groupList of a contact. It is within at least one group, because I added it to favourites, yet still getGroupList called on that contact returns an empty list. Is it a bug, or am I missing something? I have not found any examples of processing group info using your library on your pages here.

**Comment by blainepwnz** [comment]
Hello @Jeffero277 ,
Can you give me steps to reproduce and expected result?

**Comment by JedrzejBlaszczak** [comment]
Hello,
I've instantied an contacts list using your builder and checked if the
first contacts groupList is empty like this
 (I May have made some syntax errors below as I am away from PC currently
and writing from my phone using what I remembered, sorry for that) :

List<ContactData> contactsList = new
ContactGetterBuilder(context).allFields().buildList();

contactsList.get(0).getGroupList().isEmpty() - and this statement returns
true for me.

The other data of that contact is correct, I am only having issue with the
groups info. Or maybe I am wrong and your library retrives favourites
contacts info in some other way, than reading it from groupList? As I have
no other groups on the phone, than favourites.

Best regards

wt., 18 lut 2020, 16:52 użytkownik Andrew Tomash <notifications@github.com>
napisał:

**Comment by blainepwnz** [comment]
Favorites == isStarred is android contacts, it is not implemented currently in library.

Groups list are useful, when user have created custom group and adding users to it, also it is helpful when you want to get google contacts, viber contacts and so on, because they are in corresponding group.

I assume, that you need to get favorite contacts, if i add boolean to ContactData, which will return true if contact is favorite and false otherwise, does is solves your problem?

**Comment by JedrzejBlaszczak** [comment]
Yes, that solution would be perfect for my needs.

wt., 18 lut 2020, 17:35 użytkownik Andrew Tomash <notifications@github.com>
napisał:

**Comment by JedrzejBlaszczak** [comment]
Sorry for bothering you again, but do you have any potential delivery date for this feature? :)

**Comment by blainepwnz** [comment]
@Jeffero277 please check 1.12.4

**Comment by JedrzejBlaszczak** [comment]
Thank you very much, works great!
