### ISSUE TITLE
Support default values for multiple contact data of the same type

### ISSUE THREAD

**Issue by Faltenreich** [blainepwnz/AndroidContacts#21]
Currently there seems no way to find out the default value for a contact with multiple contact data of the same type, e.g. a contact having multiple mobile phone numbers. The [Google Contacts](https://play.google.com/store/apps/details?id=com.google.android.contacts) app for example shows the addition "Standard" next to the label for such a phone number.

The only thing I have found in this direction was [Withlabel.getDefaultLabelId()](https://github.com/blainepwnz/AndroidContacts/blob/3fa4cd7147e7e456b95253eff5fd4b0f368e1491/androidcontacts/src/main/java/com/tomash/androidcontacts/contactgetter/interfaces/WithLabel.java#L68), but this method is protected and therefor not visible outside of this library. Maybe you could make this public or provide another method in order to get the default value? Please correct me if I am missing something. 

Thanks in advance and best regards from Germany!

**Comment by blainepwnz** [comment]
Hey!
I don't know if it is going to work, but can you try this?
```
val isStandart = somePhoneNumbe.getLabelId() == PhoneNumber.TYPE_HOME
```
I feel like it is something you are looking for.

**Comment by Faltenreich** [comment]
Yes, this answers my question sort of. This will work as long as TYPE_HOME will stay default for PhoneNumber. If you decide to change this, my code will break as I am statically registering TYPE_HOME as default. Maybe you could make getDefaultLabelId() public, so users of your library are able to adapt to potential API changes?

I am not sure how Google is marking the default number (maybe they are counting calls and register the number with the most calls?) but that seems a topic for another discussion independent of your awesome library. :)

**Comment by blainepwnz** [comment]
I am updating library, when there is some potential issue, also I am not breaking backward compatibility, so you are safe :)
If I plan to change something - I will ping you in that thread.
