### ISSUE TITLE
Full name is always null when querying with phone number

### ISSUE THREAD

**Issue by iqbalza** [blainepwnz/AndroidContacts#24]
Whenever i try querying with phone number, the full name is always null even when composite name is not.

**Comment by blainepwnz** [comment]
Can you provide me a code example and expected result?

**Comment by iqbalza** [comment]
lets say i have a contact named John Doe and i want to query this contact using its phone number

 ```
val contact = ContactsGetterBuilder(app)
                    .withPhone(phoneNumber)
                    .firstOrNull()
                Timber.d("name:${contact.compositeName}") //John Doe
                Timber.d("name:${contact.nameData.fullName}") //null
                Timber.d("name:${contact.nameData.firstName}") //null
                Timber.d("name:${contact.nameData.surname}") //null
```

**Comment by blainepwnz** [comment]
nameData is received from another table, so composite name should be always non null.
To get name data try something like this.
```
val contact = ContactsGetterBuilder(app)
                   .withPhone(phoneNumber)
                   .addField(NAME_DATA)
                   .firstOrNull()
```

**Comment by iqbalza** [comment]
> nameData is received from another table, so composite name should be always non null.
> To get name data try something like this.
> 
> ```
> val contact = ContactsGetterBuilder(app)
>                    .withPhone(phoneNumber)
>                    .addField(NAME_DATA)
>                    .firstOrNull()
> ```

Thanks! It's working now. 

 I have another question. If a contact have multiple phone numbers, i can only seems to query the contact with the first phone number.

Suppose John Doe have 2 phone numbers

```
ContactsGetterBuilder(app)
.withPhone(firstPhoneNumber)
.firstOrNull() // this will return John Doe 

ContactsGetterBuilder(app)
.withPhone(secondPhoneNumber)
.firstOrNull() // this will return null
```

**Comment by blainepwnz** [comment]
I have created test where I have inserted contact and added 3 numbers 
```
contact.phoneList.add(PhoneNumber("+631230001234", "1234"))
contact.phoneList.add(PhoneNumber("1230001234", "1234"))
contact..phoneList.add(PhoneNumber("123000", "1234"))

Assert.assertEquals(1, getList { withPhone("1230001234") }.size)
Assert.assertEquals(1, getList { withPhone("+631230001234") }.size)
Assert.assertEquals(1, getList { withPhone("123000") }.size)
```
And it is working.
Maybe you have pluses there or secondPhoneNumber contains space or something wrong with data?
try to get all contacts and see what the difference between your number and numbers in phone

**Comment by blainepwnz** [comment]
take a look at test from #25

**Comment by iqbalza** [comment]
Thanks, You're right! Apparently the first number have dashes but the second one doesn't and that was what causing the issue. Is it possible to ignore special characters like "-" or "+" when querying the contact with phone number?

**Comment by blainepwnz** [comment]
try withPhoneLike instead of withPhone
