### ISSUE TITLE
difference between CompositeName and FullName

### ISSUE THREAD

**Issue by Mateeen** [blainepwnz/AndroidContacts#30]
can you please tell what is the difference between ContactData.getCompositeName() and ContactData.getNameData().getFullName()

**Comment by blainepwnz** [comment]
hey!
In most of cases they are the same, I get it from different tables.
Composite name from contact table.
Full name from NameData tables.
If you just need full name of user I feel like composite name would be enough.
So it is handled on android side.
According to official documentation full name from contact data is
```
            /**
             * The name that should be used to display the contact.
             * <i>Unstructured component of the name should be consistent with
             * its structured representation.</i>
             * <p>
             * Type: TEXT
             */
```
Composite name is
```
        /**
         * The display name for the contact.
         * <P>Type: TEXT</P>
         */
```

**Comment by Mateeen** [comment]
I need the full name of the contact. Which one is recommended and more reliable? Please suggest. 
Thanks

**Comment by blainepwnz** [comment]
Get composite name from ContactData
