### ISSUE TITLE
Not all contacts have a phone

### ISSUE THREAD

**Issue by Pirokar** [blainepwnz/AndroidContacts#35]
For example, I have a contact "Mother" that have a phone numer. But query

ContactsGetterBuilder(context)
                .withNameLike("mother")
                .buildList()

returns contact, but not returning a phone. Phone list is empty.

**Comment by blainepwnz** [comment]
for the sake of performance you define yourself what fields do you need.
For example if you need phone numbers you should call
```
ContactsGetterBuilder(context)
    .addField(FieldType.PHONE_NUMBERS)
    .withNameLike("mother")
    .buildList()
```
If you want to get all data you cal call
```
ContactsGetterBuilder(context)
    .allFields()
    .withNameLike("mother")
    .buildList()
```

Hope it helps!

**Comment by Pirokar** [comment]
Yes! It's my fault! Sorry and thanks! :)
