### ISSUE TITLE
Is it possible to search contacts where name STARTS from sequence first, and then if name contains sequence?

### ISSUE THREAD

**Issue by Pirokar** [blainepwnz/AndroidContacts#36]
Will be very cool to have this feature

**Comment by blainepwnz** [comment]
can you give me an example with entry data and expected behavior?

**Comment by Pirokar** [comment]
For example, I searching "Mother". When I typing "M", then "o" I expected to see first that starting with "Mo...". But instead of this I have "Daromo", "Fimond" and etc first,

**Comment by Pirokar** [comment]
https://drive.google.com/file/d/1DZCfH0kZl1QR0x1CTgdCQz5BqXL69ms7/view?usp=sharing - this is the video explanation. I typing "мама"

**Comment by blainepwnz** [comment]
i think the better way is to do it on your side.
```
val contactsStartingWithText = contacts.filter { it.displayname.startsWith(prefix) }
val result = contactsStartingWithText + (contacts - contactsStartingWithText)
```

**Comment by Pirokar** [comment]
Yes, I can do it. But you have "withNameLike" and I thought that will be cool to have such sorting there
