### ISSUE TITLE
How to get main phone number?

### ISSUE THREAD

**Issue by Pirokar** [blainepwnz/AndroidContacts#38]
If one contact has several phones, hot to get the main?

**Comment by blainepwnz** [comment]
i assume it should be first in list of numbers

**Comment by Pirokar** [comment]
Unfortunately no. The first is not default

**Comment by blainepwnz** [comment]
i will take a look on it later

**Comment by Pirokar** [comment]
https://stackoverflow.com/questions/6474019/how-to-detect-the-default-phone-number-of-a-contact-if-set - can you implement it, please?

**Comment by blainepwnz** [comment]
it is always false, also I don't understand what do you mean by default account, since there is nothing in UI to make phone number default or primary

**Comment by Pirokar** [comment]
Phone has UI to set  default number
![Screenshot_20210417-183503_Contacts](https://user-images.githubusercontent.com/12714628/115118466-e9764b80-9fab-11eb-9f55-0080bb498112.jpg)

**Comment by blainepwnz** [comment]
added in 1.14.2
https://github.com/blainepwnz/AndroidContacts/pull/40

**Comment by Pirokar** [comment]
Cool! How its working now, Andrew?) How to define default number?

**Comment by blainepwnz** [comment]
to define default number i need to implement edit contact, which I have not implemented.(and don't have any plans to implement)
Other way is to create new contact via ContactSaver and to add PhoneNumber into it with "isPrimary" set to true.

**Comment by Pirokar** [comment]
Maybe I was incorrect with my question. As I understand, you implemented getting default number now. How to work with it? How to get default number?

**Comment by blainepwnz** [comment]
ContactData.phoneList.first().isPrimary()

**Comment by Pirokar** [comment]
Cool! Thank you!)
