### ISSUE TITLE
JCenter is closed

### ISSUE THREAD

**Issue by ThomasGorisse** [blainepwnz/AndroidContacts#42]
Hi,

Thanks for your lib.
Would you mind putting it on mavenCentral?
I personally use this for publishing: https://github.com/vanniktech/gradle-maven-publish-plugin
It's simple and quick to use.

Thanks

**Comment by blainepwnz** [comment]
Hi!

I hope can get some spare time on a weekend, what is the deadline for bintray, April 2022 iirc?

**Comment by percula** [comment]
I just used JitPack, which builds directly from the GitHub source code. You can simply change your dependency to:

```groovy
implementation("com.github.blainepwnz:AndroidContacts:1.14.0")
```

**Comment by blainepwnz** [comment]
thanks @percula , it works fine.
I have updated readme with new dependency pointing to jitpack.
