### ISSUE TITLE
Specifying photo field

### ISSUE THREAD

**Issue by behelit** [blainepwnz/AndroidContacts#5]
There's no `FieldType.PHOTO`, how would you specify the query to include only certain fields like email but also photo?

```
List<ContactData> contacts = new ContactsGetterBuilder(getContext())
                    .addField(FieldType.EMAILS, FieldType.PHONE_NUMBERS, FieldType.PHOTO)
                    .buildList();
```

**Comment by blainepwnz** [comment]
@behelit photo uri is received by default, no need to add this field explicitly.
Also if you want to get contacts only with photos you can use onlyWithPhoto() option.
