### ISSUE TITLE
Contacts accounts

### ISSUE THREAD

**Issue by Lurgainn** [blainepwnz/AndroidContacts#6]
I'm trying to develop a little utility to backup/restore offline all contacts, included contacts created on phone local account, and I want to try to use your library, but I never see the field '**account**' used in your code.
I'm wrong? And if not, is there a possibility to implement something like **getAccount()** **setAccount()** in your library?

I really need this feature because I want to use my app also to migrate contacts between different ROMs, so I need to be able to modify the account of the contacts while restoring them. For example, actually all my contacts in my phone with LineageOS 14.1 (Nougat) are stored under the local account "**PHONE**" (I don't trust Google to give them all my contacts), but if I want to migrate to LineageOS 15.1 (Oreo), I have to be able to modify the account of every single contact while restoring, because in Oreo the default local offline account is "**DEVICE**" and not the old "PHONE". So while I process the contacts, I need to know to which account belongs every single contact.

Can you help me? I will be grateful for any info.
Thanks again

**Comment by blainepwnz** [comment]
@Lurgainn There is no such a feature with getting and setting account, but i will check the code and try to implement it.

**Comment by Lurgainn** [comment]
But if actually there's not any reference to the accounts, that means (for example) that when I save a new contact with ContactsSaverBuilder, it will be saved under the default account with no way to select others. Is it correct?
Thanks very much for all your work.

**Comment by blainepwnz** [comment]
@Lurgainn I am testing now account types.
On my test phone i have some contacts, their account type is com.google and account name is my email.
Are these fields what would you like to get and save?
About contact saver, i will add dependency on account type and account name, so you can save new contacts using account you selected.
Don't know when i will finish it, because i would like also to cover it with tests to prevent regressions.

**Comment by blainepwnz** [comment]
@Lurgainn check please 1.12.0 release.

**Comment by Lurgainn** [comment]
WOW!!! Thank you very much for your so quick update. In the next days I'll begin to develop my app (I'm not a professional developer, so it will need some time ;) )
Thanks again.
